=== FlorianGaiser/DBIS02/XML_SchemaDok.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2022 (x64) (http://www.altova.com) von Daniel Jovanovic (HTWG-Konstant) bearbeitet -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:altova="http://www.altova.com/xml-schema-extensions" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Ferienwohnungsagentur">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Kunde" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Vorname" type="xs:string"/>
							<xs:element name="E-Mailadresse" type="xs:string"/>
							<xs:element name="Geburtsdatum" type="xs:date"/>
							<xs:element name="Telefonnummer"/>
							<xs:element name="Bankverbindung">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="22" fixed="false"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Adresse" type="xs:integer"/>
						</xs:sequence>
						<xs:attribute name="Kundennummer" type="xs:integer" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Bankverbindung" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Kontonummer" type="xs:integer"/>
							<xs:element name="Bankleitzahl" type="xs:integer"/>
							<xs:element name="BIC" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="IBAN" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Adresse" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Strasse" type="xs:string"/>
							<xs:element name="Hausnummer" type="xs:string"/>
							<xs:element name="Postleitzeahl" type="xs:string"/>
							<xs:element name="Ort" type="xs:integer"/>
						</xs:sequence>
						<xs:attribute name="AdressenID" type="xs:integer" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Ort" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Land" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="OrtID" type="xs:integer" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Land" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ISO-Code" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Ferienwohnung" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Zimmeranzahl">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Größe">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="PreisProTag">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:assertion test="$value gt 0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="TextuelleBeschreibung" type="xs:string"/>
							<xs:element name="Adresse" type="xs:integer" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="Wohnungsnummer" type="xs:integer" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Bild" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="BildID" type="xs:integer"/>
							<xs:element name="Bildbeschreibung" type="xs:string"/>
							<xs:element name="Ferienwohnung" type="xs:integer"/>
						</xs:sequence>
						<xs:attribute name="Dateipfad" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Zusatzausstattung" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="Beschreibung" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="FewoZusatz" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Wohnungsnummer" type="xs:integer"/>
							<xs:element name="Zusatzausattung" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Belegung" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Reservierungsdatum" type="xs:date"/>
							<xs:element name="Statusflag">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Buchung"/>
										<xs:enumeration value="Reservierung"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Anreisedatum" type="xs:date"/>
							<xs:element name="Abreisedatum" type="xs:date"/>
							<xs:element name="Ferienwohnung" type="xs:integer"/>
							<xs:element name="Kunde" type="xs:integer"/>
						</xs:sequence>
						<xs:attribute name="Belegungsnummer" type="xs:integer" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:keyref name="BelegungKunde" refer="KundenID">
			<xs:selector xpath="Belegung"/>
			<xs:field xpath="Kunde"/>
		</xs:keyref>
		<xs:keyref name="BelegungFewo" refer="Ferienwohnung">
			<xs:selector xpath="Belegung"/>
			<xs:field xpath="Ferienwohnung"/>
		</xs:keyref>
		<xs:key name="Belegung">
			<xs:selector xpath="Belegung"/>
			<xs:field xpath="@Belegungsnummer"/>
		</xs:key>
		<xs:keyref name="FewoZusatzZ" refer="Zusatzausstattung">
			<xs:selector xpath="FewoZusatz"/>
			<xs:field xpath="Zusatzausattung"/>
		</xs:keyref>
		<xs:keyref name="FewoZusatzW" refer="Ferienwohnung">
			<xs:selector xpath="FewoZusatz"/>
			<xs:field xpath="Wohnungsnummer"/>
		</xs:keyref>
		<xs:key name="FewoZusatz">
			<xs:selector xpath="FewoZusatz"/>
			<xs:field xpath="Zusatzausattung"/>
			<xs:field xpath="Wohnungsnummer"/>
		</xs:key>
		<xs:key name="Zusatzausstattung">
			<xs:selector xpath="Zusatzausstattung"/>
			<xs:field xpath="@Beschreibung"/>
		</xs:key>
		<xs:keyref name="BildVonFewo" refer="Ferienwohnung">
			<xs:selector xpath="Bild"/>
			<xs:field xpath="Ferienwohnung"/>
		</xs:keyref>
		<xs:key name="Bild">
			<xs:selector xpath="Bild"/>
			<xs:field xpath="@Dateipfad"/>
		</xs:key>
		<xs:keyref name="FewoAdresse" refer="AdressenID">
			<xs:selector xpath="Ferienwohnung"/>
			<xs:field xpath="Adresse"/>
		</xs:keyref>
		<xs:key name="Ferienwohnung">
			<xs:selector xpath="Ferienwohnung"/>
			<xs:field xpath="@Wohnungsnummer"/>
		</xs:key>
		<xs:keyref name="OrtVonLand" refer="Landname">
			<xs:selector xpath="Ort"/>
			<xs:field xpath="Land"/>
		</xs:keyref>
		<xs:key name="Landname">
			<xs:selector xpath="Land"/>
			<xs:field xpath="@Name"/>
		</xs:key>
		<xs:keyref name="AdresseVonOrt" refer="OrtID">
			<xs:selector xpath="Adresse"/>
			<xs:field xpath="Ort"/>
		</xs:keyref>
		<xs:key name="OrtID">
			<xs:selector xpath="Ort"/>
			<xs:field xpath="@OrtID"/>
		</xs:key>
		<xs:keyref name="KundenAdresse" refer="AdressenID">
			<xs:selector xpath="Kunde"/>
			<xs:field xpath="Adresse"/>
		</xs:keyref>
		<xs:key name="AdressenID">
			<xs:selector xpath="Adresse"/>
			<xs:field xpath="@AdressenID"/>
		</xs:key>
		<xs:keyref name="Kundenbank" refer="IBAN">
			<xs:selector xpath="Kunde"/>
			<xs:field xpath="Bankverbindung"/>
		</xs:keyref>
		<xs:key name="KundenID">
			<xs:selector xpath="Kunde"/>
			<xs:field xpath="@Kundennummer"/>
		</xs:key>
		<xs:key name="IBAN">
			<xs:selector xpath="Bankverbindung"/>
			<xs:field xpath="@IBAN"/>
		</xs:key>
		<xs:unique name="BLZKontoNr">
			<xs:selector xpath="Bankverbindung"/>
			<xs:field xpath="Kontonummer"/>
			<xs:field xpath="Bankleitzahl"/>
		</xs:unique>
	</xs:element>
</xs:schema>

=== FlorianGaiser/DBIS02/XML_InstanzDok.xml
<?xml version="1.0" encoding="UTF-8"?><Ferienwohnungsagentur xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/danie/Desktop/HTWG_KN/Semester4/Dbis2/XML/Ferienwohnungsagentur/XML_SchemaDok.xsd">	<Kunde Kundennummer="1">		<Name>Napf</Name>		<Vorname>Karl</Vorname>		<E-Mailadresse>knapf@gmx.de</E-Mailadresse>		<Geburtsdatum>1960-01-01</Geburtsdatum>		<Telefonnummer>07531-123456</Telefonnummer>		<Bankverbindung>DE71692717230007823212</Bankverbindung>		<Adresse>1</Adresse>	</Kunde>	<Kunde Kundennummer="2">		<Name>Meier</Name>		<Vorname>Hans</Vorname>		<E-Mailadresse>meiers.hans@t-online.de</E-Mailadresse>		<Geburtsdatum>1975-01-02</Geburtsdatum>		<Telefonnummer>06221-999888</Telefonnummer>		<Bankverbindung>DE71327939680008929368</Bankverbindung>		<Adresse>2</Adresse>	</Kunde>	<Kunde Kundennummer="3">		<Name>Huber</Name>		<Vorname>Franz</Vorname>		<E-Mailadresse>huber@t-online.de</E-Mailadresse>		<Geburtsdatum>1980-01-03</Geburtsdatum>		<Telefonnummer>0711-554673</Telefonnummer>		<Bankverbindung>DE71692717230001347291</Bankverbindung>		<Adresse>3</Adresse>	</Kunde>	<Kunde Kundennummer="4">		<Name>Eber</Name>		<Vorname>Klaus</Vorname>		<E-Mailadresse>eber@bluewin.ch</E-Mailadresse>		<Geburtsdatum>1985-01-04</Geburtsdatum>		<Telefonnummer>+41-171-9864785</Telefonnummer>		<Bankverbindung>CH56297884310008792978</Bankverbindung>		<Adresse>4</Adresse>	</Kunde>	<Kunde Kundennummer="5">		<Name>Meier</Name>		<Vorname>Egon</Vorname>		<E-Mailadresse>meier@gmail.com</E-Mailadresse>		<Geburtsdatum>1990-01-05</Geburtsdatum>		<Telefonnummer>+41-171-9864785</Telefonnummer>		<Bankverbindung>CH56878902710009082780</Bankverbindung>		<Adresse>5</Adresse>	</Kunde>	<Kunde Kundennummer="6">		<Name>Knopf</Name>		<Vorname>Jim</Vorname>		<E-Mailadresse>jim.knopf@gmx.net</E-Mailadresse>		<Geburtsdatum>1995-01-06</Geburtsdatum>		<Telefonnummer>0171-9876543</Telefonnummer>		<Bankverbindung>DE71692717230007322890</Bankverbindung>		<Adresse>6</Adresse>	</Kunde>	<Bankverbindung IBAN="DE71692717230007823212">		<Kontonummer>7823212</Kontonummer>		<Bankleitzahl>69271723</Bankleitzahl>		<BIC>1234DE56789</BIC>	</Bankverbindung>	<Bankverbindung IBAN="DE71327939680008929368">		<Kontonummer>8929368</Kontonummer>		<Bankleitzahl>32793968</Bankleitzahl>		<BIC>1234DE56789</BIC>	</Bankverbindung>	<Bankverbindung IBAN="DE71692717230001347291">		<Kontonummer>1347291</Kontonummer>		<Bankleitzahl>69271723</Bankleitzahl>		<BIC>1234DE56789</BIC>	</Bankverbindung>	<Bankverbindung IBAN="CH56297884310008792978">		<Kontonummer>8792978</Kontonummer>		<Bankleitzahl>29788431</Bankleitzahl>		<BIC>9876CH54321</BIC>	</Bankverbindung>	<Bankverbindung IBAN="CH56878902710009082780">		<Kontonummer>9082780</Kontonummer>		<Bankleitzahl>87890271</Bankleitzahl>		<BIC>9876CH54322</BIC>	</Bankverbindung>	<Bankverbindung IBAN="DE71692717230007322890">		<Kontonummer>7322890</Kontonummer>		<Bankleitzahl>69271723</Bankleitzahl>		<BIC>1234DE56789</BIC>	</Bankverbindung>	<Adresse AdressenID="1">		<Strasse>Reutestr.</Strasse>		<Hausnummer>104</Hausnummer>		<Postleitzeahl>78467</Postleitzeahl>		<Ort>11</Ort>	</Adresse>	<Adresse AdressenID="2">		<Strasse>Hauptstr.</Strasse>		<Hausnummer>12</Hausnummer>		<Postleitzeahl>69115</Postleitzeahl>		<Ort>9</Ort>	</Adresse>	<Adresse AdressenID="3">		<Strasse>Schlossstr.</Strasse>		<Hausnummer>54</Hausnummer>		<Postleitzeahl>70173</Postleitzeahl>		<Ort>15</Ort>	</Adresse>	<Adresse AdressenID="4">		<Strasse>Alpenstr.</Strasse>		<Hausnummer>11</Hausnummer>		<Postleitzeahl>3001</Postleitzeahl>		<Ort>3</Ort>	</Adresse>	<Adresse AdressenID="5">		<Strasse>Seeweg</Strasse>		<Hausnummer>23</Hausnummer>		<Postleitzeahl>8001</Postleitzeahl>		<Ort>16</Ort>	</Adresse>	<Adresse AdressenID="6">		<Strasse>Rheingutstr.</Strasse>		<Hausnummer>14</Hausnummer>		<Postleitzeahl>78462</Postleitzeahl>		<Ort>11</Ort>	</Adresse>	<Adresse AdressenID="7">		<Strasse>Highway</Strasse>		<Hausnummer>5</Hausnummer>		<Postleitzeahl>2349</Postleitzeahl>		<Ort>12</Ort>	</Adresse>	<Adresse AdressenID="8">		<Strasse>Markgrafenstr.</Strasse>		<Hausnummer>33</Hausnummer>		<Postleitzeahl>78461</Postleitzeahl>		<Ort>11</Ort>	</Adresse>	<Adresse AdressenID="9">		<Strasse>Zur Piste</Strasse>		<Hausnummer>189</Hausnummer>		<Postleitzeahl>2234</Postleitzeahl>		<Ort>5</Ort>	</Adresse>	<Adresse AdressenID="10">		<Strasse>rue Monsieur</Strasse>		<Hausnummer>980</Hausnummer>		<Postleitzeahl>8234</Postleitzeahl>		<Ort>4</Ort>	</Adresse>	<Adresse AdressenID="11">		<Strasse>ue de gaulle</Strasse>		<Hausnummer>22</Hausnummer>		<Postleitzeahl>8787</Postleitzeahl>		<Ort>6</Ort>	</Adresse>	<Adresse AdressenID="12">		<Strasse>rue de la Maison Blanche</Strasse>		<Hausnummer>32</Hausnummer>		<Postleitzeahl>8792</Postleitzeahl>		<Ort>13</Ort>	</Adresse>	<Adresse AdressenID="13">		<Strasse>rue liberte</Strasse>		<Hausnummer>78</Hausnummer>		<Postleitzeahl>8792</Postleitzeahl>		<Ort>13</Ort>	</Adresse>	<Adresse AdressenID="14">		<Strasse>Strandweg</Strasse>		<Hausnummer>90</Hausnummer>		<Postleitzeahl>2321</Postleitzeahl>		<Ort>1</Ort>	</Adresse>	<Adresse AdressenID="15">		<Strasse>Strandweg</Strasse>		<Hausnummer>91</Hausnummer>		<Postleitzeahl>2321</Postleitzeahl>		<Ort>1</Ort>	</Adresse>	<Adresse AdressenID="16">		<Strasse>Calle del torro</Strasse>		<Hausnummer>821</Hausnummer>		<Postleitzeahl>5221</Postleitzeahl>		<Ort>2</Ort>	</Adresse>	<Adresse AdressenID="17">		<Strasse>Strandweg</Strasse>		<Hausnummer>45</Hausnummer>		<Postleitzeahl>2321</Postleitzeahl>		<Ort>1</Ort>	</Adresse>	<Adresse AdressenID="18">		<Strasse>Aeropuerto de Barcelona</Strasse>		<Hausnummer>10</Hausnummer>		<Postleitzeahl>08820</Postleitzeahl>		<Ort>2</Ort>	</Adresse>	<Adresse AdressenID="19">		<Strasse>Am Flughafen</Strasse>		<Hausnummer>2</Hausnummer>		<Postleitzeahl>60541</Postleitzeahl>		<Ort>8</Ort>	</Adresse>	<Adresse AdressenID="20">		<Strasse>Sabiha Gökcen</Strasse>		<Hausnummer>1</Hausnummer>		<Postleitzeahl>1452</Postleitzeahl>		<Ort>10</Ort>	</Adresse>	<Adresse AdressenID="21">		<Strasse>Charles de Gaulle</Strasse>		<Hausnummer>1</Hausnummer>		<Postleitzeahl>8792</Postleitzeahl>		<Ort>13</Ort>	</Adresse>	<Adresse AdressenID="22">		<Strasse>Flughafen-Allee</Strasse>		<Hausnummer>100</Hausnummer>		<Postleitzeahl>5098</Postleitzeahl>		<Ort>16</Ort>	</Adresse>	<Adresse AdressenID="23">		<Strasse>Europapark</Strasse>		<Hausnummer>1</Hausnummer>		<Postleitzeahl>78231</Postleitzeahl>		<Ort>14</Ort>	</Adresse>	<Adresse AdressenID="24">		<Strasse>Seestr.</Strasse>		<Hausnummer>12</Hausnummer>		<Postleitzeahl>78463</Postleitzeahl>		<Ort>11</Ort>	</Adresse>	<Adresse AdressenID="25">		<Strasse>Bergweg</Strasse>		<Hausnummer>78</Hausnummer>		<Postleitzeahl>2371</Postleitzeahl>		<Ort>7</Ort>	</Adresse>	<Adresse AdressenID="26">		<Strasse>GreenOne</Strasse>		<Hausnummer>29</Hausnummer>		<Postleitzeahl>1352</Postleitzeahl>		<Ort>16</Ort>	</Adresse>	<Adresse AdressenID="27">		<Strasse>rue de gaulle</Strasse>		<Hausnummer>10</Hausnummer>		<Postleitzeahl>8787</Postleitzeahl>		<Ort>6</Ort>	</Adresse>	<Ort OrtID="1">		<Name>Antalya</Name>		<Land>Türkei</Land>	</Ort>	<Ort OrtID="2">		<Name>Barcelona</Name>		<Land>Spanien</Land>	</Ort>	<Ort OrtID="3">		<Name>Bern</Name>		<Land>Schweiz</Land>	</Ort>	<Ort OrtID="4">		<Name>Bordeaux</Name>		<Land>Frankreich</Land>	</Ort>	<Ort OrtID="5">		<Name>Chur</Name>		<Land>Schweiz</Land>	</Ort>	<Ort OrtID="6">		<Name>Disneyland</Name>		<Land>Frankreich</Land>	</Ort>	<Ort OrtID="7">		<Name>Flims-Laax</Name>		<Land>Schweiz</Land>	</Ort>	<Ort OrtID="8">		<Name>Frankfurt</Name>		<Land>Deutschland</Land>	</Ort>	<Ort OrtID="9">		<Name>Heidelberg</Name>		<Land>Deutschland</Land>	</Ort>	<Ort OrtID="10">		<Name>Istanbul</Name>		<Land>Türkei</Land>	</Ort>	<Ort OrtID="11">		<Name>Konstanz</Name>		<Land>Deutschland</Land>	</Ort>	<Ort OrtID="12">		<Name>Öludeniz</Name>		<Land>Türkei</Land>	</Ort>	<Ort OrtID="13">		<Name>Paris</Name>		<Land>Frankreich</Land>	</Ort>	<Ort OrtID="14">		<Name>Rust</Name>		<Land>Deutschland</Land>	</Ort>	<Ort OrtID="15">		<Name>Stuttgart</Name>		<Land>Deutschland</Land>	</Ort>	<Ort OrtID="16">		<Name>Zürich</Name>		<Land>Schweiz</Land>	</Ort>	<Land Name="Deutschland">		<ISO-Code>DE </ISO-Code>	</Land>	<Land Name="Frankreich">		<ISO-Code>FR </ISO-Code>	</Land>	<Land Name="Schweiz">		<ISO-Code>CH </ISO-Code>	</Land>	<Land Name="Spanien">		<ISO-Code>ES </ISO-Code>	</Land>	<Land Name="Türkei">		<ISO-Code>TR </ISO-Code>	</Land>	<Land Name="Grönland">		<ISO-Code>GL </ISO-Code>	</Land>	<Ferienwohnung Wohnungsnummer="1">		<Zimmeranzahl>6</Zimmeranzahl>		<Größe>200</Größe>		<PreisProTag>349</PreisProTag>		<TextuelleBeschreibung>Finka</TextuelleBeschreibung>		<Adresse>7</Adresse>	</Ferienwohnung>	<Ferienwohnung Wohnungsnummer="2">		<Zimmeranzahl>2</Zimmeranzahl>		<Größe>45</Größe>		<PreisProTag>120</PreisProTag>		<TextuelleBeschreibung>Ferienwohnung mit Seeblick</TextuelleBeschreibung>		<Adresse>8</Adresse>	</Ferienwohnung>	<Ferienwohnung Wohnungsnummer="3">		<Zimmeranzahl>3</Zimmeranzahl>		<Größe>150</Größe>		<PreisProTag>249</PreisProTag>		<TextuelleBeschreibung>im Schnee</TextuelleBeschreibung>		<Adresse>9</Adresse>	</Ferienwohnung>	<Ferienwohnung Wohnungsnummer="4">		<Zimmeranzahl>4</Zimmeranzahl>		<Größe>100</Größe>		<PreisProTag>249</PreisProTag>		<TextuelleBeschreibung>direkt am Meer</TextuelleBeschreibung>		<Adresse>10</Adresse>	</Ferienwohnung>	<Ferienwohnung Wohnungsnummer="5">		<Zimmeranzahl>3</Zimmeranzahl>		<Größe>110</Größe>		<PreisProTag>289</PreisProTag>		<TextuelleBeschreibung>direkt am Park</TextuelleBeschreibung>		<Adresse>11</Adresse>	</Ferienwohnung>	<Ferienwohnung Wohnungsnumme
